use crate::colors::{Hsla, ThemeColors};

pub fn aineer_dark_colors() -> ThemeColors {
    ThemeColors {
        background: Hsla::from_hex("#1e1e2e"),
        background_surface: Hsla::from_hex("#232334"),
        background_elevated: Hsla::from_hex("#2a2a3c"),
        background_input: Hsla::from_hex("#232334"),
        text_primary: Hsla::from_hex("#e0e0e8"),
        text_secondary: Hsla::from_hex("#8888a0"),
        text_muted: Hsla::from_hex("#5c5c72"),
        text_on_accent: Hsla::from_hex("#ffffff"),
        accent_primary: Hsla::from_hex("#5b9cf5"),
        accent_ai: Hsla::from_hex("#b07aff"),
        accent_agent: Hsla::from_hex("#f0a050"),
        status_error: Hsla::from_hex("#f06060"),
        status_warning: Hsla::from_hex("#e8c040"),
        status_success: Hsla::from_hex("#50c878"),
        status_info: Hsla::from_hex("#70a8e8"),
        border_default: Hsla::from_hex("#3a3a4e"),
        border_focus: Hsla::from_hex("#5b9cf5"),
        command_block_bg: Hsla::from_hex("#232334"),
        command_block_prompt_bg: Hsla::from_hex("#272738"),
        ai_block_bg: Hsla::from_hex("#232334"),
        agent_block_bg: Hsla::from_hex("#232334"),
        tool_block_bg: Hsla::from_hex("#232334"),
        system_block_bg: Hsla::from_hex("#232334"),
        activity_bar_bg: Hsla::from_hex("#1a1a28"),
        activity_bar_active: Hsla::from_hex("#5b9cf5"),
        status_bar_bg: Hsla::from_hex("#1a1a28"),
        tab_active_bg: Hsla::from_hex("#232334"),
        tab_inactive_bg: Hsla::from_hex("#1e1e2e"),
        sidebar_bg: Hsla::from_hex("#1e1e2e"),
        scrollbar_thumb: Hsla::from_hex("#5c5c72"),
        scrollbar_thumb_hover: Hsla::from_hex("#8888a0"),
    }
}

pub fn aineer_light_colors() -> ThemeColors {
    ThemeColors {
        background: Hsla::from_hex("#f8f8fc"),
        background_surface: Hsla::from_hex("#ffffff"),
        background_elevated: Hsla::from_hex("#f0f0f4"),
        background_input: Hsla::from_hex("#ffffff"),
        text_primary: Hsla::from_hex("#1e1e2e"),
        text_secondary: Hsla::from_hex("#6e6e82"),
        text_muted: Hsla::from_hex("#9a9ab0"),
        text_on_accent: Hsla::from_hex("#ffffff"),
        accent_primary: Hsla::from_hex("#3070d0"),
        accent_ai: Hsla::from_hex("#8050d0"),
        accent_agent: Hsla::from_hex("#c07020"),
        status_error: Hsla::from_hex("#d04040"),
        status_warning: Hsla::from_hex("#c09020"),
        status_success: Hsla::from_hex("#30a060"),
        status_info: Hsla::from_hex("#3080c0"),
        border_default: Hsla::from_hex("#d0d0dc"),
        border_focus: Hsla::from_hex("#3070d0"),
        command_block_bg: Hsla::from_hex("#ffffff"),
        command_block_prompt_bg: Hsla::from_hex("#f4f4f8"),
        ai_block_bg: Hsla::from_hex("#ffffff"),
        agent_block_bg: Hsla::from_hex("#ffffff"),
        tool_block_bg: Hsla::from_hex("#ffffff"),
        system_block_bg: Hsla::from_hex("#ffffff"),
        activity_bar_bg: Hsla::from_hex("#eaeaf0"),
        activity_bar_active: Hsla::from_hex("#3070d0"),
        status_bar_bg: Hsla::from_hex("#eaeaf0"),
        tab_active_bg: Hsla::from_hex("#ffffff"),
        tab_inactive_bg: Hsla::from_hex("#f0f0f4"),
        sidebar_bg: Hsla::from_hex("#f4f4f8"),
        scrollbar_thumb: Hsla::from_hex("#c0c0cc"),
        scrollbar_thumb_hover: Hsla::from_hex("#a0a0b0"),
    }
}
